core/urls.py
from django.urls import path

from .views import (
    ContactUsDeleteView,
    ContactUsListView,
    DashboardView,
    FAQCreateView,
    FAQDeleteView,
    FAQListView,
    FAQUpdateView,
    SiteSettingView,
    HomeView,
    AboutUsView,
    ContactUsView,
    TermsAndConditionView,
    PrivacyPolicyView,
    FAQView,
)

app_name = "core"
urlpatterns = [
    path(r"admin/", DashboardView.as_view(), name="dashboard"),
    path(r"admin/settings/", SiteSettingView.as_view(), name="site_settings"),
    # contact_us
    path(r"admin/contact_us/", ContactUsListView.as_view(), name="admin_contact_us"),
    path(
        r"admin/contact_us/delete/<int:pk>/",
        ContactUsDeleteView.as_view(),
        name="delete_contact_us",
    ),
    # faq
    path(r"admin/faq/", FAQListView.as_view(), name="admin_faq"),
    path(r"admin/faq/add", FAQCreateView.as_view(), name="add_faq"),
    path(r"admin/faq/edit/<int:pk>/", FAQUpdateView.as_view(), name="edit_faq"),
    path(r"admin/faq/delete/<int:pk>/", FAQDeleteView.as_view(), name="delete_faq"),
    # customer urls
    path(r"", HomeView.as_view(), name="home"),
    path(r"about_us/", AboutUsView.as_view(), name="about_us"),
    path(r"contact_us/", ContactUsView.as_view(), name="contact_us"),
    path(
        r"terms_and_conditions/",
        TermsAndConditionView.as_view(),
        name="terms_and_conditions",
    ),
    path(r"privacy_policy/", PrivacyPolicyView.as_view(), name="privacy_policy"),
    path(r"faq/", FAQView.as_view(), name="faq"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("", include("core.urls")),
    path("", include("property.urls")),
    path("", include("accounts.urls")),
    path("", include("advertisement.urls")),
    path("", include("subscription.urls")),
    path("", include("review.urls")),
] + debug_toolbar_urls()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path

from .views import (
    CustomerPropertyCreateView,
    LikeView,
    PropertyCreateView,
    PropertyDeleteView,
    PropertyDetailView,
    PropertyListingView,
    PropertyListView,
    PropertyUpdateView,
    TypeCreateView,
    TypeDeleteView,
    TypeListView,
    TypeUpdateView,
)

app_name = "property"
urlpatterns = [
    # types
    path(r"admin/types/", TypeListView.as_view(), name="types"),
    path(r"admin/types/add", TypeCreateView.as_view(), name="add_type"),
    path(r"admin/types/edit/<int:pk>/", TypeUpdateView.as_view(), name="edit_type"),
    path(r"admin/types/delete/<int:pk>/", TypeDeleteView.as_view(), name="delete_type"),
    # properties
    path(r"admin/properties/", PropertyListView.as_view(), name="properties"),
    path(r"admin/properties/add", PropertyCreateView.as_view(), name="add_property"),
    path(
        r"admin/properties/edit/<int:pk>/",
        PropertyUpdateView.as_view(),
        name="edit_property",
    ),
    path(
        r"admin/properties/delete/<int:pk>/",
        PropertyDeleteView.as_view(),
        name="delete_property",
    ),
    path(r"properties/", PropertyListingView.as_view(), name="property_list"),
    path(r"properties/<int:pk>/", PropertyDetailView.as_view(), name="property"),
    path(
        r"properties/add",
        CustomerPropertyCreateView.as_view(),
        name="add_customer_property",
    ),
    path(r"properties/<int:pk>/like", LikeView.as_view(), name="add_like"),
]

subscription/urls.py
from django.urls import path

from .views import (
    CheckoutCancelView,
    CheckoutSessionCreateView,
    CheckoutSuccessView,
    CustomerSubscriptonListView,
    StripeConfigView,
    SubscriptionPlanCreateView,
    SubscriptionPlanDeleteView,
    SubscriptionPlanListView,
    SubscriptionPlanUpdateView,
    UserSubscriptionListView,
    stripe_webhook,
)

app_name = "subscription"
urlpatterns = [
    path(
        r"admin/subscription_plans/",
        SubscriptionPlanListView.as_view(),
        name="subscription_plans",
    ),
    path(
        r"admin/subscription_plans/add",
        SubscriptionPlanCreateView.as_view(),
        name="add_subscription_plan",
    ),
    path(
        r"admin/subscription_plans/edit/<int:pk>/",
        SubscriptionPlanUpdateView.as_view(),
        name="edit_subscription_plan",
    ),
    path(
        r"admin/subscription_plans/delete/<int:pk>/",
        SubscriptionPlanDeleteView.as_view(),
        name="delete_subscription_plan",
    ),
    path(
        r"admin/user_subscriptions/",
        UserSubscriptionListView.as_view(),
        name="user_subscriptions",
    ),
    path(
        r"subscriptions/",
        CustomerSubscriptonListView.as_view(),
        name="customer_subscription_plans",
    ),
    path(
        r"subscriptions/checkout/", CheckoutSessionCreateView.as_view(), name="checkout"
    ),
    path(r"subscriptions/config/", StripeConfigView.as_view(), name="stripe_config"),
    path(r"subscriptions/success/", CheckoutSuccessView.as_view(), name="success"),
    path(r"subscriptions/cancel/", CheckoutCancelView.as_view(), name="cancel"),
    path(r"subscriptions/stripe_webhook/", stripe_webhook),
]

project/templates/customer/pages/about_us.html
{% extends "customer/base.html" %}
{% load static %}

{% block title %}About Us{% endblock %}

{% block content %}
    {% url "core:about_us" as title_url %}
    {% include "customer/partials/breadcrumb.html" with title="Home" subtitle="About Us" title_url=title_url %}

    <section class="about-us pb-6">
        <div class="container">
            <div class="about-image-box">
                <div class="row d-flex align-items-center justify-content-between">
                    {{object.description|safe}}
                </div>
            </div>
        </div>
    </section>

    <section class="about-us bg-white pb-6 pt-0">
        <div class="container">
            <div class="why-us">
                <div class="why-us-box">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-sm-6 mb-4">
                            <div class="why-us-item text-center bg-lgrey">
                                <div class="why-us-icon">
                                    <i class="flaticon-call theme"></i>
                                </div>
                                <div class="why-us-content">
                                    <h4><a>Trusted By Thousands</a></h4>
                                    <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 mb-4">
                            <div class="why-us-item text-center bg-lgrey">
                                <div class="why-us-icon">
                                    <i class="flaticon-global theme"></i>
                                </div>
                                <div class="why-us-content">
                                    <h4><a>Wide Renge Properties</a></h4>
                                    <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 mb-4">
                            <div class="why-us-item text-center bg-lgrey">
                                <div class="why-us-icon">
                                    <i class="flaticon-building theme"></i>
                                </div>
                                <div class="why-us-content">
                                    <h4><a>Financing Made Easy</a></h4>
                                    <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 mb-4">
                            <div class="why-us-item text-center bg-lgrey">
                                <div class="why-us-icon">
                                    <i class="flaticon-location-pin theme"></i>
                                </div>
                                <div class="why-us-content">
                                    <h4><a>We are here near you</a></h4>
                                    <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% include "customer/partials/looking_to_buy.html" %}
    {% include "customer/partials/exclusive.html" %}
    
    <section class="newsletter p-0 position-relative">
        <div class="newsletter-main bg-theme2 p-5 pb-3">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-8 mb-2">
                        <div class="newsletter-content">
                            <h2 class="mb-0 white text-lg-start text-center">Do You Need Help With Anything?</h2>
                        </div>
                    </div>
                    <div class="col-lg-4 mb-2">
                        <div class="newsletter-form w-100">
                            <form action="#" method="get" accept-charset="utf-8" class="border-0">
                                <input type="text" placeholder="Email Address">
                                <button class="nir-btn-black">Subscribe</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

project/templates/customer/pages/contact_us.html
{% extends "customer/base.html" %}
{% load static %}

{% block title %}Contact Us{% endblock %}

{% block content %}
    <section class="contact-main pt-0 pb-10 bg-grey">
        <div class="map">
            <div style="width: 100%">
                <iframe height="500" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>
            </div>
        </div>
        <div class="container">
            <div class="contact-info-main">
                <div class="row">
                    <div class="col-lg-10 col-offset-lg-1 mx-auto">
                        <div class="contact-info bg-white pt-10 pb-10 px-5">
                            <div class="contact-info-title text-center mb-4 px-5">
                                <h3 class="mb-1">INFORMATION ABOUT US</h3>
                                <p class="mb-0">Sagittis posuere id nam quis vestibulum vestibulum a facilisi at elit hendrerit scelerisque sodales nam dis orci.</p>
                            </div>
                            <div class="contact-info-content row mb-1">
                                <div class="col-lg-4 col-md-6 mb-4">
                                    <div class="info-item bg-lgrey px-4 py-5 border-all text-center">
                                        <div class="info-icon mb-2">
                                            <i class="fa fa-map-marker"></i>
                                        </div>
                                        <div class="info-content">
                                            <p class="m-0">{{object.address}}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-6 mb-4">
                                    <div class="info-item bg-lgrey px-4 py-5 border-all text-center">
                                        <div class="info-icon mb-2">
                                            <i class="fa fa-phone"></i>
                                        </div>
                                        <div class="info-content">
                                            <p class="m-0">{{object.phone}}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-12 mb-4">
                                    <div class="info-item bg-lgrey px-4 py-5 border-all text-center">
                                        <div class="info-icon mb-2">
                                            <i class="fa fa-envelope"></i>
                                        </div>
                                        <div class="info-content ps-4">
                                            <p class="m-0">{{object.email}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="contact-form1" class="contact-form px-5">
                                <div class="contact-info-title text-center mb-4 px-5">
                                    <h3 class="mb-1">Keep in Touch</h3>
                                    <p class="mb-0">Fundpress site thoughtfully designed for real humans which means the best user experience for your entire community.</p>
                                </div>
                                <div id="contactform-error-msg"></div>

                                <form method="post" action="{% url "core:contact_us" %}" name="contact_us" id="contact_us">
                                    {% csrf_token %}
                                    <div class="form-group mb-2">
                                        <input type="text" name="first_name" class="form-control" id="fullname" placeholder="First Name"/>
                                    </div>
                                    <div class="form-group mb-2">
                                        <input type="text" name="last_name" class="form-control" id="llastname" placeholder="Last Name"/>
                                    </div>
                                    <div class="form-group mb-2">
                                        <input type="email" name="email" class="form-control" id="email" placeholder="Email"/>
                                    </div>
                                    <div class="form-group mb-2">
                                        <input type="text" name="phone" class="form-control" id="phnumber" placeholder="Phone"/>
                                    </div>
                                    <div class="textarea mb-2">
                                        <textarea name="message" placeholder="Enter a message"></textarea>
                                    </div>
                                    <div class="comment-btn text-center">
                                        <input type="submit" class="nir-btn" id="submit2" value="Send Message"/>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="content-line m-0">
        <div class="content-line-inner bg-theme2 pb-6 pt-6 p-5">
            <div class="container">
                <div class="row d-md-flex align-items-center justify-content-between text-lg-start text-center" >
                    <div class="col-lg-9">
                        <h2 class="mb-0 white">Looking for a dream home?</h2>
                        <p class="white">We can help you realize your dream of a new home</p>
                    </div>
                    <div class="col-lg-3">
                        <a href="{% url "property:property_list" %}" class="nir-btn-black float-lg-end float-none">Fine More Properties</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/templates/customer/pages/listing.html
{% extends "customer/base.html" %}
{% load static property_extras %}

{% block title %}Properties{% endblock %}

{% block content %}
  {% url "property:property_list" as title_url %}
  {% include "customer/partials/breadcrumb.html" with title="Dashboard" subtitle="Listing" title_url=title_url %}
  
  <section class="blog">
    <div class="container">
      <div class="row flex-row-reverse">
        <div class="col-lg-8">
          <div class="listing-inner">
            <div class="list-results d-flex align-items-center justify-content-between">
              <div class="list-results-sort">
                <p class="m-0">Showing {{ page_obj.object_list.count }} of {{ page_obj.paginator.count }} results</p>
              </div>
              <div class="click-menu d-flex align-items-center justify-content-between">
                <div class="sortby d-flex align-items-center justify-content-between ml-2">
                  <a href="{% url "property:property_list" %}" class="me-2">Clear Filters</a>
                  <form action="{% url "property:property_list" %}" method="get">
                    <select class="niceSelect" name="sort" onchange="this.form.submit()">
                      <option value="">Sort By</option>
                      <option {% if request.GET.sort == "rating" %}selected{% endif %} value="rating">Rating</option>
                      <option {% if request.GET.sort == "price" %}selected{% endif %} value="price">Price: low to high</option>
                      <option {% if request.GET.sort == "-price" %}selected{% endif %} value="-price">Price: high to low</option>
                    </select>
                  </form>
                </div>
              </div>
            </div>
            {% for object in object_list %}
              <div class="blog-full mb-4 border-b pb-4">
                <div class="row">
                  <div class="col-lg-5 col-md-4">
                    <div class="blog-image">
                      <a href="#" style="background-image: url({{object.images.0.image.url}});"></a>
                    </div>
                  </div>
                  <div class="col-lg-7 col-md-8">
                    <div class="blog-content">
                      <h5 class="theme mb-2">{{object.type.name}}</h5>
                      <h4 class="mb-2">
                        <a href="{% url "property:property" pk=object.pk %}" class="">{{object.name}}</a>
                      </h4>
                      <div class="d-flex align-items-center justify-content-between border-b pb-1 mb-2">
                        <div class="entry-price">Start From<span class="d-block theme fw-bold">Rs. {{object.details.price}}</span>
                        </div>
                        <div class="entry-metalist d-flex align-items-center">
                          <ul>
                            <li class="me-2"><i class="fa fa-eye"></i></li>
                            <li class="me-2">
                              {% has_liked_by request.user object as has_liked %}
                              <form action="{% url "property:add_like" pk=object.pk %}" method="get">
                                <button style="background-color:transparent;" type="submit">
                                  {% if has_liked %}
                                    <i class="fa fa-heart"></i>
                                  {% else %}
                                    <i class="fa fa-heart" style="font-weight:100"></i>
                                  {% endif %}
                                </button>
                              </form>
                            </li>
                          </ul>
                        </div>
                      </div>
                      <p class="mb-2">{{object.address}}</p>
                      <div class="css-1bcji2n pb-1">By
                        <a class="css-l2kny5"><span data-q="dev-name">Samarth Drushti Developers</span></a><span data-q="dev-name">(Builder)</span>
                      </div>
                      <ul class="d-flex align-items-center justify-content-between bg-grey p-3 px-4">
                        <li class="me-2"><i class="fa fa-eye"></i> 3 Beds</li>
                        <li class="me-2">
                          <i class="fa fa-heart"></i> 2 Baths
                        </li>
                        <li><i class="fa fa-comments"></i> 600 Sq Ft</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}

            {% if object_list %}
              <div class="pagination-main text-center">
                <ul class="pagination">
                  {% if page_obj.has_previous %}
                    <li><a href="?page={{page_obj.previous_page_number}}"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a></li>
                  {% endif %}
                  {% for page in page_obj.paginator.page_range %}
                    {% if page_obj.number == page %}
                      <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                    {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                      <li><a href="?page={{ page }}">{{ page }}</a></li>
                    {% endif %}
                  {% endfor %}
                  {% if page_obj.has_next %}
                    <li><a href="?page={{page_obj.next_page_number}}"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a></li>
                  {% endif %}
                </ul>
              </div>
            {% endif %}
          </div>
        </div>

        <!-- sidebar -->
        {% include "customer/partials/filter-card.html" %}
        <!-- sidebar -->
      </div>
    </div>
  </section>

  {% include "customer/partials/looking_to_buy.html" %}
  {% include "customer/partials/email_subscribe.html" %}
{% endblock %}


{% block extra_body %}
  <script>
    
  </script>
{% endblock %}

project/templates/customer/pages/password-reset.html
{% extends "customer/base.html" %}
{% load static widget_tweaks %}

{% block title %}Forgot Password{% endblock %}

{% block content %}
    {% url "core:home" as title_url %}
    {% include "customer/partials/breadcrumb.html" with title="Home" subtitle="Forgot Password" title_url=title_url %}

    <div id="dashboard" class="pt-10 pb-10">
        <div class="container">
            <div class="dashboard-main">
                <div class="row">
                    <div class="dashboard-content">
                        <div class="add-listing dashboard-form">
                            <div class="listing-main">
                                <div class="addlist-inner bg-white">
                                    <div class="addlist-content bg-white">
                                        <form method="post">
                                            {% csrf_token %}
                                            {{form.as_p}}
                                            <div class="col-lg-12">
                                                <button type="submit" class="nir-btn">Submit</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_body %}
    <script src="{% static "customer/js/jpanelmenu.min.js" %}"></script>
    <script src="{% static "customer/js/dashboard-custom.js" %}"></script>
{% endblock %}
 

project/templates/customer/pages/privacy_policy.html
{% extends "customer/base.html" %}
{% load static %}

{% block title %}Privacy Policy{% endblock %}

{% block content %}
    {% url "core:privacy_policy" as title_url %}
    {% include "customer/partials/breadcrumb.html" with title="Home" subtitle="Privacy Policy" title_url=title_url %}

    <div class="about-section pt-30 pb-30">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    {{object.description|safe}}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/templates/customer/pages/subscription_plan.html
{% extends "customer/base.html" %}
{% load static %}

{% block title %}Subscription Plans{% endblock %}

{% block extra_head %}
    <script src="https://js.stripe.com/v3/"></script>
{% endblock %}

{% block content %}
    {% url "core:home" as title_url %}
    {% include "customer/partials/breadcrumb.html" with title="Home" subtitle="Subscription Plans" title_url=title_url %}

    <section  id="subscription_plan" class="bg-lgrey border-bottom border-t pb-6">
        <div class="container">
            <div class="section-title mb-6 pb-1 w-75 mx-auto text-center">
                <h2 class="m-0">Featured <span>Pricing</span></h2>
                <p>Subscribe to Premium today to save 50,000 on brokerage, along with other benefits.</p>
            </div>  
            <div class="row">
                {% for object in object_list %}
                    <div class="col-lg-4 col-md-12 mb-4">
                        <div class="pkg-container text-center box-shadow p-4 border">
                            <div class="pg-title position-relative">
                                {% if request.user.subscription.plan == object %}
                                    <span class="position-absolute top-0 start-100 translate-middle p-2 bg-success border border-light rounded-circle"></span>
                                {% endif %}
                                <i class="icon fas fa-rocket display-6 bg-theme1 mb-2 white"></i>
                                <h4 class="theme mb-0">{{object.name}}</h4>
                                <h2 class="theme2"><i class="fas fa-rupee-sign"></i> {{object.price}}</h2>
                            </div>
                            <div class="pg-main">
                                <ul class='d-flex flex-column'>
                                    <li><i class="fas fa-check"></i> <strong class='text-success'>{{ object.max_listings }}</strong> Property Listings</li>
                                    <li><i class="fas fa-check"></i> <strong class='text-success'>{{ object.max_ads }}</strong> Advertisements</li>
                                </ul>
                                <div>
                                    {{object.description|safe}}
                                </div>
                                {% if request.user.subscription.plan != object %}
                                    <button class="btn nir-btn mt-2" onclick="SubscribePlan({{object.id}})">Subscribe</button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

    {% include "customer/partials/looking_to_buy.html" %}
    {% include "customer/partials/exclusive.html" %}
    
    <section class="newsletter p-0 position-relative">
        <div class="newsletter-main bg-theme2 p-5 pb-3">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-8 mb-2">
                        <div class="newsletter-content">
                            <h2 class="mb-0 white text-lg-start text-center">Do You Need Help With Anything?</h2>
                        </div>
                    </div>
                    <div class="col-lg-4 mb-2">
                        <div class="newsletter-form w-100">
                            <form action="#" method="get" accept-charset="utf-8" class="border-0">
                                <input type="text" placeholder="Email Address">
                                <button class="nir-btn-black">Subscribe</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block extra_body %}
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        function SubscribePlan(id){
            let csrftoken = getCookie('csrftoken');

            fetch('{% url "subscription:stripe_config" %}',{
                method: "GET",
                headers: {
                    'X-CSRFToken': csrftoken,
                },
            })
            .then(res=>res.json())
            .then(data=>{
                const stripe = Stripe(data.publicKey);
                
                fetch('{% url "subscription:checkout" %}',{
                    method: "POST",
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrftoken,
                    },
                    body: JSON.stringify({'plan_id': id})
                })
                .then(res=>res.json())
                .then(data=>{
                    console.log(data);
                    return stripe.redirectToCheckout({sessionId: data.sessionId})
                });
            })
        }
    </script>
{% endblock %}

project/templates/customer/pages/terms_and_condition.html
{% extends "customer/base.html" %}
{% load static %}

{% block title %}Terms & Conditions{% endblock %}

{% block content %}
    {% url "core:terms_and_conditions" as title_url %}
    {% include "customer/partials/breadcrumb.html" with title="Home" subtitle="Terms & Conditions" title_url=title_url %}

    <div class="about-section pt-30 pb-30">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    {{object.description|safe}}
                </div>
            </div>
        </div>
    </div>
{% endblock %}