accounts/urls.py
from django.urls import path

from .views import (
    AdminLoginView,
    AdminLogoutView,
    ChangePasswordView,
    CustomerDashboardView,
    CustomerHistoryView,
    CustomerListingView,
    CustomerLoginView,
    CustomerLogoutView,
    CustomerProfileView,
    CustomerRegisterView,
    CustomerReviewView,
    GroupCreateView,
    GroupDeleteView,
    GroupListView,
    GroupUpdateView,
    PasswordResetConfirmView,
    PasswordResetView,
    UserCreateView,
    UserDeleteView,
    UserListView,
    UserUpdateView,
)

app_name = "accounts"
urlpatterns = [
    path(r"admin/login/", AdminLoginView.as_view(), name="admin_login"),
    path(r"admin/logout/", AdminLogoutView.as_view(), name="admin_logout"),
    # users
    path(r"admin/users/", UserListView.as_view(), name="users"),
    path(r"admin/users/add", UserCreateView.as_view(), name="add_user"),
    path(r"admin/users/edit/<int:pk>/", UserUpdateView.as_view(), name="edit_user"),
    path(r"admin/users/delete/<int:pk>/", UserDeleteView.as_view(), name="delete_user"),
    # groups
    path(r"admin/groups/", GroupListView.as_view(), name="groups"),
    path(r"admin/groups/add", GroupCreateView.as_view(), name="add_group"),
    path(r"admin/groups/edit/<int:pk>/", GroupUpdateView.as_view(), name="edit_group"),
    path(
        r"admin/groups/delete/<int:pk>/", GroupDeleteView.as_view(), name="delete_group"
    ),
    # customer
    path(r"logout/", CustomerLogoutView.as_view(), name="logout"),
    path(r"password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path(
        r"password_reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(r"accounts/", CustomerDashboardView.as_view(), name="dashboard"),
    path(
        r"accounts/change-password/",
        ChangePasswordView.as_view(),
        name="change_password",
    ),
    path(r"accounts/register/", CustomerRegisterView.as_view(), name="register"),
    path(r"accounts/login/", CustomerLoginView.as_view(), name="login"),
    path(r"accounts/history/", CustomerHistoryView.as_view(), name="history"),
    path(r"accounts/reviews/", CustomerReviewView.as_view(), name="reviews"),
    path(r"accounts/listing/", CustomerListingView.as_view(), name="listing"),
    path(r"accounts/profile/", CustomerProfileView.as_view(), name="profile"),
]

core/urls.py
from django.urls import path

from .views import (
    ContactUsDeleteView,
    ContactUsListView,
    DashboardView,
    FAQCreateView,
    FAQDeleteView,
    FAQListView,
    FAQUpdateView,
    SiteSettingView,
    HomeView,
    AboutUsView,
    ContactUsView,
    TermsAndConditionView,
    PrivacyPolicyView,
    FAQView,
)

app_name = "core"
urlpatterns = [
    path(r"admin/", DashboardView.as_view(), name="dashboard"),
    path(r"admin/settings/", SiteSettingView.as_view(), name="site_settings"),
    # contact_us
    path(r"admin/contact_us/", ContactUsListView.as_view(), name="admin_contact_us"),
    path(
        r"admin/contact_us/delete/<int:pk>/",
        ContactUsDeleteView.as_view(),
        name="delete_contact_us",
    ),
    # faq
    path(r"admin/faq/", FAQListView.as_view(), name="admin_faq"),
    path(r"admin/faq/add", FAQCreateView.as_view(), name="add_faq"),
    path(r"admin/faq/edit/<int:pk>/", FAQUpdateView.as_view(), name="edit_faq"),
    path(r"admin/faq/delete/<int:pk>/", FAQDeleteView.as_view(), name="delete_faq"),
    # customer urls
    path(r"", HomeView.as_view(), name="home"),
    path(r"about_us/", AboutUsView.as_view(), name="about_us"),
    path(r"contact_us/", ContactUsView.as_view(), name="contact_us"),
    path(
        r"terms_and_conditions/",
        TermsAndConditionView.as_view(),
        name="terms_and_conditions",
    ),
    path(r"privacy_policy/", PrivacyPolicyView.as_view(), name="privacy_policy"),
    path(r"faq/", FAQView.as_view(), name="faq"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("", include("core.urls")),
    path("", include("property.urls")),
    path("", include("accounts.urls")),
    path("", include("advertisement.urls")),
    path("", include("subscription.urls")),
    path("", include("review.urls")),
] + debug_toolbar_urls()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/customer/pages/customer/profile.html
{% extends "customer/base.html" %}
{% load static widget_tweaks %}

{% block title %}Profile{% endblock %}

{% block extra_head %}
    <!--dashboard CSS-->
    <link href="{% static "customer/css/dashboard.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    {% url "accounts:profile" as title_url %}
    {% include "customer/partials/breadcrumb.html" with title="Dashboard" subtitle="My Profile" title_url=title_url %}

    <div id="dashboard" class="pt-10 pb-10">
        <div class="container">
            <div class="dashboard-main">
                <div class="row">
                    {% include "customer/partials/profile-card.html" %}
                    <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">    
                        <div class="dashboard-content">
                            <div class="dashboard-form mb-4">
                                <div class="row">

                                    <!-- Profile -->
                                    <div class="col-lg-12 col-md-12 col-xs-12">
                                        <div class="dashboard-list">
                                            <h4 class="gray">Profile Details</h4>
                                            <form action="{% url "accounts:profile" %}" method="post" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div class="dashboard-list-static">
                                                    <div class="form-group mb-2">
                                                        <label>Profile Image *</label>
                                                        {{form.profile|attr:"accept:image/*"}}
                                                        {% if form.errors %}<p class="text-danger">{{form.errors.profile}}</p>{% endif %}
                                                    </div>
                                                    <div class="form-group mb-2">
                                                        <label>Username *</label>
                                                        <input value="{{request.user.username}}" name="username" type="text">
                                                        {% if form.errors %}<p class="text-danger">{{form.errors.username}}</p>{% endif %}
                                                    </div>
                                                    <div class="form-group mb-2">
                                                        <label>Email Address *</label>
                                                        <input value="{{request.user.email}}" name="email" type="text">
                                                        {% if form.errors %}<p class="text-danger">{{form.errors.email}}</p>{% endif %}
                                                    </div>
                                                    <div class="form-group mb-2">
                                                        <label>Phone Number *</label>
                                                        <input value="{{request.user.phone}}" name="phone" type="text">
                                                        {% if form.errors %}<p class="text-danger">{{form.errors.phone}}</p>{% endif %}
                                                    </div>

                                                    <div class="row mb-2">
                                                        <div class="col-lg-6 col-md-6 col-xs-12">
                                                            <label>Company Name</label>
                                                            <input type="text" name="company" value="{{request.user.company}}">
                                                            {% if form.errors %}<p class="text-danger">{{form.errors.company}}</p>{% endif %}
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-xs-12">
                                                            <label>Address *</label>
                                                            <input type="text" name="address" value="{{request.user.address}}">
                                                            {% if form.errors %}<p class="text-danger">{{form.errors.address}}</p>{% endif %}
                                                        </div>
                                                    </div>

                                                    <div class="row mb-2">
                                                        <div class="col-lg-6 col-md-6 col-xs-12">
                                                            <label class="twitter-input"><i class="fab fa-twitter"></i> Twitter</label>
                                                            <input value="{{request.user.twitter}}" name="twitter" type="text">
                                                            {% if form.errors %}<p class="text-danger">{{form.errors.twitter}}</p>{% endif %}
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-xs-12">
                                                            <label class="facebook-input"><i class="fab fa-facebook"></i> Facebook</label>
                                                            <input value="{{request.user.facebook}}" name="facebook" type="text">
                                                            {% if form.errors %}<p class="text-danger">{{form.errors.facebook}}</p>{% endif %}
                                                        </div>
                                                    </div>
                                                    <div class="row mb-2">
                                                        <div class="col-lg-6 col-md-6 col-xs-12">
                                                            <label class="skype-input"><i class="fab fa-skype"></i> Skype</label>
                                                            <input value="{{request.user.skype}}" name="skype" type="text">
                                                            {% if form.errors %}<p class="text-danger">{{form.errors.skype}}</p>{% endif %}
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-xs-12">
                                                            <label class="linkedin-input"><i class="fab fa-linkedin"></i> LinkedIn</label>
                                                            <input value="{{request.user.linkedin}}" name="linkedin" type="text">
                                                            {% if form.errors %}<p class="text-danger">{{form.errors.linkedin}}</p>{% endif %}
                                                        </div>
                                                    </div>
                                                    <div class="row mb-2">
                                                        <div class="col-lg-6 col-md-6 col-xs-12">
                                                            <label class="instagram-input"><i class="fab fa-instagram"></i> Instagram</label>
                                                            <input value="{{request.user.instagram}}" name="instagram" type="text">
                                                            {% if form.errors %}<p class="text-danger">{{form.errors.instagram}}</p>{% endif %}
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-xs-12">
                                                            <label class="pinterest-input"><i class="fab fa-pinterest"></i> Pinterest</label>
                                                            <input value="{{request.user.pinterest}}" name="pinterest" type="text">
                                                            {% if form.errors %}<p class="text-danger">{{form.errors.pinterest}}</p>{% endif %}
                                                        </div>
                                                    </div>
                                                    <div class="form-btn">
                                                        <button type="submit" class="nir-btn">SAVE CHANGE</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="dashboard-form mb-4">
                                <div class="dashboard-password">
                                    <h4>Change Password</h4>
                                    <form method="post" action="{% url "accounts:change_password" %}">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                                <div class="form-group mb-2">
                                                    <label>Current Password</label>
                                                    <input type="password" name="old_password" placeholder="*********">
                                                </div>
                                                {% if form.errors %}<p class="text-danger">{{form.errors.old_password}}</p>{% endif %}
                                            </div>
                                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                                <div class="form-group mb-2">
                                                    <label>New Password</label>
                                                    <input type="password" name="new_password1">
                                                </div>
                                                {% if form.errors %}<p class="text-danger">{{form.errors.new_password1}}</p>{% endif %}
                                            </div>
                                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                                <div class="form-group mb-2">
                                                    <label>Re-enter Password</label>
                                                    <input type="password" name="new_password2">
                                                </div>
                                                {% if form.errors %}<p class="text-danger">{{form.errors.new_password2}}</p>{% endif %}
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-btn mar-top-15">
                                                    <button type="submit" class="nir-btn">SAVE CHANGE</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>    
            </div>    
            <!-- Content / End -->
        </div>
    </div>
    <!-- Dashboard / End -->


    <!-- content-line start -->
    <section class="newsletter p-0 position-relative">
        <div class="newsletter-main bg-theme2 p-5 pb-3">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-8 mb-2">
                        <div class="newsletter-content">
                            <h2 class="mb-0 white text-lg-start text-center">
                                Do You Need Help With Anything?
                            </h2>
                        </div>
                    </div>
                    <div class="col-lg-4 mb-2">
                        <div class="newsletter-form w-100">
                            <form action="#" method="get" accept-charset="utf-8" class="border-0">
                                <input type="text" placeholder="Email Address">
                                <button class="nir-btn-black">Subscribe</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block extra_body %}
    <script src="{% static "customer/js/dashboard-custom.js" %}"></script>
{% endblock %}

project/templates/customer/pages/customer/reviews.html
{% extends "customer/base.html" %}
{% load static %}

{% block title %}Reviews{% endblock %}

{% block extra_head %}
    <!--dashboard CSS-->
    <link href="{% static "customer/css/dashboard.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    {% url "accounts:reviews" as title_url %}
    {% include "customer/partials/breadcrumb.html" with title="Dashboard" subtitle="Reviews" title_url=title_url %}

    <div id="dashboard" class="pt-10 pb-10">
        <div class="container">
            <div class="dashboard-main">
                <div class="row">
                    {% include "customer/partials/profile-card.html" %}

                    <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">    
                        <div class="dashboard-content">
                            <div class="dashboard-review single-comments">
                                <div class="comments">
                                    <div class="comment-box d-flex align-items-center justify-content-between">
                                        <div class="comment-image">
                                            <img src="{% static "customer/images/lead_profile/photo-1607346256330-dee7af15f7c5.jpg" %}" alt="image">
                                        </div>
                                        <div class="comment-content">
                                            <h4 class="mb-1">Nishchay</h4>
                                            <p class="comment-date mb-2">January 25, 2024 at 10:46 am</p>
                                            <span class="num-rating white">4.6/5</span>
                                            <span class="comment-title"><i>"Was too noisy and not suitable for business meetings"</i></span>
                                            <p class="comment mt-2">Take in the iconic skyline and visit the neighbourhood hangouts that you've only ever seen on TV. Take in the iconic skyline and visit the neighbourhood.</p>
                                        </div>
                                    </div>

                                    <div class="comment-box d-flex align-items-center justify-content-between">
                                        <div class="comment-image">
                                            <img src="{% static "customer/images/lead_profile/photo-1607346256330-dee7af15f7c5.jpg" %}" alt="image">
                                        </div>
                                        <div class="comment-content">
                                            <h4 class="mb-1">Nishchay</h4>
                                            <p class="comment-date mb-2">January 25, 2024 at 10:46 am</p>
                                            <span class="num-rating white">4.6/5</span>
                                            <span class="comment-title"><i>"Was too noisy and not suitable for business meetings"</i></span>
                                            <p class="comment mt-2">Take in the iconic skyline and visit the neighbourhood hangouts that you've only ever seen on TV. Take in the iconic skyline and visit the neighbourhood.</p>
                                        </div>
                                    </div>

                                    <div class="comment-box d-flex align-items-center justify-content-between">
                                        <div class="comment-image">
                                            <img src="{% static "customer/images/lead_profile/photo-1607346256330-dee7af15f7c5.jpg" %}" alt="image">
                                        </div>
                                        <div class="comment-content">
                                            <h4 class="mb-1">Nishchay</h4>
                                            <p class="comment-date mb-2">January 25, 2024 at 10:46 am</p>
                                            <span class="num-rating white">4.6/5</span>
                                            <span class="comment-title"><i>"Was too noisy and not suitable for business meetings"</i></span>
                                            <p class="comment mt-2">Take in the iconic skyline and visit the neighbourhood hangouts that you've only ever seen on TV. Take in the iconic skyline and visit the neighbourhood.</p>
                                        </div>
                                    </div>

                                    <div class="comment-box d-flex align-items-center justify-content-between">
                                        <div class="comment-image">
                                            <img src="{% static "customer/images/lead_profile/photo-1607346256330-dee7af15f7c5.jpg" %}" alt="image">
                                        </div>
                                        <div class="comment-content">
                                            <h4 class="mb-1">Nishchay</h4>
                                            <p class="comment-date mb-2">January 25, 2024 at 10:46 am</p>
                                            <span class="num-rating white">4.6/5</span>
                                            <span class="comment-title"><i>"Was too noisy and not suitable for business meetings"</i></span>
                                            <p class="comment mt-2">Take in the iconic skyline and visit the neighbourhood hangouts that you've only ever seen on TV. Take in the iconic skyline and visit the neighbourhood.</p>
                                        </div>
                                    </div>

                                    <div class="comment-box d-flex align-items-center justify-content-between">
                                        <div class="comment-image">
                                            <img src="{% static "customer/images/lead_profile/photo-1607346256330-dee7af15f7c5.jpg" %}" alt="image">
                                        </div>
                                        <div class="comment-content">
                                            <h4 class="mb-1">Nishchay</h4>
                                            <p class="comment-date mb-2">January 25, 2024 at 10:46 am</p>
                                            <span class="num-rating white">4.6/5</span>
                                            <span class="comment-title"><i>"Was too noisy and not suitable for business meetings"</i></span>
                                            <p class="comment mt-2">Take in the iconic skyline and visit the neighbourhood hangouts that you've only ever seen on TV. Take in the iconic skyline and visit the neighbourhood.</p>
                                        </div>
                                    </div>

                                    <div class="comment-box d-flex align-items-center justify-content-between">
                                        <div class="comment-image">
                                            <img src="{% static "customer/images/lead_profile/photo-1607346256330-dee7af15f7c5.jpg" %}" alt="image">
                                        </div>
                                        <div class="comment-content">
                                            <h4 class="mb-1">Nishchay</h4>
                                            <p class="comment-date mb-2">January 25, 2024 at 10:46 am</p>
                                            <span class="num-rating white">4.6/5</span>
                                            <span class="comment-title"><i>"Was too noisy and not suitable for business meetings"</i></span>
                                            <p class="comment mt-2">Take in the iconic skyline and visit the neighbourhood hangouts that you've only ever seen on TV. Take in the iconic skyline and visit the neighbourhood.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="pagination-main text-center">
                                    <ul class="pagination">
                                        <li><a href="#"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a></li>
                                        <li class="active"><a href="#">1</a></li>
                                        <li><a href="#">2</a></li>
                                        <li><a href="#">3</a></li>
                                        <li><a href="#">4</a></li>
                                        <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>    
            </div>    
            <!-- Content / End -->
        </div>
    </div>
    <!-- Dashboard / End -->


    <!-- content-line start -->
    <section class="newsletter p-0 position-relative">
        <div class="newsletter-main bg-theme2 p-5 pb-3">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-8 mb-2">
                        <div class="newsletter-content">
                            <h2 class="mb-0 white text-lg-start text-center">
                                Do You Need Help With Anything?
                            </h2>
                        </div>
                    </div>
                    <div class="col-lg-4 mb-2">
                        <div class="newsletter-form w-100">
                            <form action="#" method="get" accept-charset="utf-8" class="border-0">
                                <input type="text" placeholder="Email Address">
                                <button class="nir-btn-black">Subscribe</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block extra_body %}
    <script src="{% static "customer/js/dashboard-custom.js" %}"></script>
{% endblock %}