accounts/urls.py
from django.urls import path

from .views import (
    AdminLoginView,
    AdminLogoutView,
    ChangePasswordView,
    CustomerDashboardView,
    CustomerHistoryView,
    CustomerListingView,
    CustomerLoginView,
    CustomerLogoutView,
    CustomerProfileView,
    CustomerRegisterView,
    CustomerReviewView,
    GroupCreateView,
    GroupDeleteView,
    GroupListView,
    GroupUpdateView,
    PasswordResetConfirmView,
    PasswordResetView,
    UserCreateView,
    UserDeleteView,
    UserListView,
    UserUpdateView,
)

app_name = "accounts"
urlpatterns = [
    path(r"admin/login/", AdminLoginView.as_view(), name="admin_login"),
    path(r"admin/logout/", AdminLogoutView.as_view(), name="admin_logout"),
    # users
    path(r"admin/users/", UserListView.as_view(), name="users"),
    path(r"admin/users/add", UserCreateView.as_view(), name="add_user"),
    path(r"admin/users/edit/<int:pk>/", UserUpdateView.as_view(), name="edit_user"),
    path(r"admin/users/delete/<int:pk>/", UserDeleteView.as_view(), name="delete_user"),
    # groups
    path(r"admin/groups/", GroupListView.as_view(), name="groups"),
    path(r"admin/groups/add", GroupCreateView.as_view(), name="add_group"),
    path(r"admin/groups/edit/<int:pk>/", GroupUpdateView.as_view(), name="edit_group"),
    path(
        r"admin/groups/delete/<int:pk>/", GroupDeleteView.as_view(), name="delete_group"
    ),
    # customer
    path(r"logout/", CustomerLogoutView.as_view(), name="logout"),
    path(r"password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path(
        r"password_reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(r"accounts/", CustomerDashboardView.as_view(), name="dashboard"),
    path(
        r"accounts/change-password/",
        ChangePasswordView.as_view(),
        name="change_password",
    ),
    path(r"accounts/register/", CustomerRegisterView.as_view(), name="register"),
    path(r"accounts/login/", CustomerLoginView.as_view(), name="login"),
    path(r"accounts/history/", CustomerHistoryView.as_view(), name="history"),
    path(r"accounts/reviews/", CustomerReviewView.as_view(), name="reviews"),
    path(r"accounts/listing/", CustomerListingView.as_view(), name="listing"),
    path(r"accounts/profile/", CustomerProfileView.as_view(), name="profile"),
]

core/urls.py
from django.urls import path

from .views import (
    ContactUsDeleteView,
    ContactUsListView,
    DashboardView,
    FAQCreateView,
    FAQDeleteView,
    FAQListView,
    FAQUpdateView,
    SiteSettingView,
    HomeView,
    AboutUsView,
    ContactUsView,
    TermsAndConditionView,
    PrivacyPolicyView,
    FAQView,
)

app_name = "core"
urlpatterns = [
    path(r"admin/", DashboardView.as_view(), name="dashboard"),
    path(r"admin/settings/", SiteSettingView.as_view(), name="site_settings"),
    # contact_us
    path(r"admin/contact_us/", ContactUsListView.as_view(), name="admin_contact_us"),
    path(
        r"admin/contact_us/delete/<int:pk>/",
        ContactUsDeleteView.as_view(),
        name="delete_contact_us",
    ),
    # faq
    path(r"admin/faq/", FAQListView.as_view(), name="admin_faq"),
    path(r"admin/faq/add", FAQCreateView.as_view(), name="add_faq"),
    path(r"admin/faq/edit/<int:pk>/", FAQUpdateView.as_view(), name="edit_faq"),
    path(r"admin/faq/delete/<int:pk>/", FAQDeleteView.as_view(), name="delete_faq"),
    # customer urls
    path(r"", HomeView.as_view(), name="home"),
    path(r"about_us/", AboutUsView.as_view(), name="about_us"),
    path(r"contact_us/", ContactUsView.as_view(), name="contact_us"),
    path(
        r"terms_and_conditions/",
        TermsAndConditionView.as_view(),
        name="terms_and_conditions",
    ),
    path(r"privacy_policy/", PrivacyPolicyView.as_view(), name="privacy_policy"),
    path(r"faq/", FAQView.as_view(), name="faq"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("", include("core.urls")),
    path("", include("property.urls")),
    path("", include("accounts.urls")),
    path("", include("advertisement.urls")),
    path("", include("subscription.urls")),
    path("", include("review.urls")),
] + debug_toolbar_urls()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path

from .views import (
    CustomerPropertyCreateView,
    LikeView,
    PropertyCreateView,
    PropertyDeleteView,
    PropertyDetailView,
    PropertyListingView,
    PropertyListView,
    PropertyUpdateView,
    TypeCreateView,
    TypeDeleteView,
    TypeListView,
    TypeUpdateView,
)

app_name = "property"
urlpatterns = [
    # types
    path(r"admin/types/", TypeListView.as_view(), name="types"),
    path(r"admin/types/add", TypeCreateView.as_view(), name="add_type"),
    path(r"admin/types/edit/<int:pk>/", TypeUpdateView.as_view(), name="edit_type"),
    path(r"admin/types/delete/<int:pk>/", TypeDeleteView.as_view(), name="delete_type"),
    # properties
    path(r"admin/properties/", PropertyListView.as_view(), name="properties"),
    path(r"admin/properties/add", PropertyCreateView.as_view(), name="add_property"),
    path(
        r"admin/properties/edit/<int:pk>/",
        PropertyUpdateView.as_view(),
        name="edit_property",
    ),
    path(
        r"admin/properties/delete/<int:pk>/",
        PropertyDeleteView.as_view(),
        name="delete_property",
    ),
    path(r"properties/", PropertyListingView.as_view(), name="property_list"),
    path(r"properties/<int:pk>/", PropertyDetailView.as_view(), name="property"),
    path(
        r"properties/add",
        CustomerPropertyCreateView.as_view(),
        name="add_customer_property",
    ),
    path(r"properties/<int:pk>/like", LikeView.as_view(), name="add_like"),
]

subscription/urls.py
from django.urls import path

from .views import (
    CheckoutCancelView,
    CheckoutSessionCreateView,
    CheckoutSuccessView,
    CustomerSubscriptonListView,
    StripeConfigView,
    SubscriptionPlanCreateView,
    SubscriptionPlanDeleteView,
    SubscriptionPlanListView,
    SubscriptionPlanUpdateView,
    UserSubscriptionListView,
    stripe_webhook,
)

app_name = "subscription"
urlpatterns = [
    path(
        r"admin/subscription_plans/",
        SubscriptionPlanListView.as_view(),
        name="subscription_plans",
    ),
    path(
        r"admin/subscription_plans/add",
        SubscriptionPlanCreateView.as_view(),
        name="add_subscription_plan",
    ),
    path(
        r"admin/subscription_plans/edit/<int:pk>/",
        SubscriptionPlanUpdateView.as_view(),
        name="edit_subscription_plan",
    ),
    path(
        r"admin/subscription_plans/delete/<int:pk>/",
        SubscriptionPlanDeleteView.as_view(),
        name="delete_subscription_plan",
    ),
    path(
        r"admin/user_subscriptions/",
        UserSubscriptionListView.as_view(),
        name="user_subscriptions",
    ),
    path(
        r"subscriptions/",
        CustomerSubscriptonListView.as_view(),
        name="customer_subscription_plans",
    ),
    path(
        r"subscriptions/checkout/", CheckoutSessionCreateView.as_view(), name="checkout"
    ),
    path(r"subscriptions/config/", StripeConfigView.as_view(), name="stripe_config"),
    path(r"subscriptions/success/", CheckoutSuccessView.as_view(), name="success"),
    path(r"subscriptions/cancel/", CheckoutCancelView.as_view(), name="cancel"),
    path(r"subscriptions/stripe_webhook/", stripe_webhook),
]

project/templates/customer/partials/breadcrumb.html
{% load static %}

<section class="breadcrumb-main pb-5 pt-20" style="background-image: url({% static "customer/images/bg/bg2.jpg" %})">
    <div class="breadcrumb-outer">
        <div class="container">
            <div class="breadcrumb-content d-md-flex align-items-center pt-6">
                <h1 class="mb-0">{{subtitle}}</h1>
                <nav aria-label="breadcrumb">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{title_url}}">{{title}}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{subtitle}}</li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="dot-overlay"></div>
</section>

project/templates/customer/partials/email_subscribe.html
<section class="newsletter p-0 position-relative">
    <div class="newsletter-main bg-theme2 p-5 pb-3">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-8 mb-2">
                    <div class="newsletter-content">
                        <h2 class="mb-0 white text-lg-start text-center">
                            Do You Need Help With Anything?
                        </h2>
                    </div>
                </div>
                <div class="col-lg-4 mb-2">
                    <div class="newsletter-form w-100">
                        <form action="#" method="get" accept-charset="utf-8" class="border-0">
                            <input type="text" placeholder="Email Address">
                            <button class="nir-btn-black">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

project/templates/customer/partials/exclusive.html
{% load static %}

<section class="our-team pt-9" style="background-image: url({% static "customer/images/shape-1.png" %});">
    <div class="container">
        <div class="section-title mb-6 pb-1 w-75 text-center mx-auto">
            <h2 class="m-0">PROPERTY VISIT <span>EXCLUSIVE IN FOCUS</span></h2>
        </div>
        <div class="team-main">
            <div class="row shop-slider">
                <div class="col-lg-3 col-md-6 col-sm-12 mb-4">
                    <div class="team-list">
                        <div class="team-image">
                            <img src="{% static "customer/images/Carousal/carousal-1.png" %}" alt="team">
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12 mb-4"> 
                    <div class="team-list">
                        <div class="team-image">
                            <img src="{% static "customer/images/Carousal/carousal-1.png" %}" alt="team">
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12 mb-4">
                    <div class="team-list">
                        <div class="team-image">
                            <img src="{% static "customer/images/Carousal/carousal-1.png" %}" alt="team">
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12 mb-4">
                    <div class="team-list">
                        <div class="team-image">
                            <img src="{% static "customer/images/Carousal/carousal-1.png" %}" alt="team">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

project/templates/customer/partials/footer.html
{% load static %}

<footer class="pt-10 footermain">
    <div class="footer-upper pb-4">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="footer-about">
                        <img src="{% static "customer/images/24_7_websitelogo.png" %}" alt="">
                        <p class="pt-2">propertyvisit.in&nbsp;is an online platform where you can buy and sell verified properties. Buying a property can change your lifestyle - So, why not invest in a reliable way for your bright future.</p>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-12 mb-4">
                    <div class="footer-links">
                        <h3 class="white">Quick link</h3>
                        <ul>
                            <li><a href="{% url "core:about_us" %}">About Us</a></li>
                            <li><a href="{% url "core:privacy_policy" %}">Privacy Policy</a></li>
                            <li><a href="{% url "core:terms_and_conditions" %}">Terms & Conditions</a></li>
                            <li><a href="{% url "subscription:customer_subscription_plans" %}">Subscription Plans</a></li>
                            <li><a href="{% url "core:faq" %}">Faq</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-12 mb-4">
                    <div class="footer-links">
                        <h3 class="white">Featured Locations</h3>
                        <ul class="res-list">
                            <li>
                                <i class="fa fa-angle-right"></i>
                                <a href="{% url "property:property_list" %}?city=hyderabad" style="margin-left: 8px;">Hyderabad</a>
                            </li>
                            <li>
                                <i class="fa fa-angle-right"></i>
                                <a href="{% url "property:property_list" %}?city=vijayawada" style="margin-left: 8px;">Vijayawada</a>
                            </li>
                            <li>
                                <i class="fa fa-angle-right"></i>
                                <a href="{% url "property:property_list" %}?city=bangalore" style="margin-left: 8px;">Bangalore</a>
                            </li>
                            <li>
                                <i class="fa fa-angle-right"></i>
                                <a href="{% url "property:property_list" %}?city=chennai" style="margin-left: 8px;">Chennai</a>
                            </li>
                            <li>
                                <i class="fa fa-angle-right"></i>
                                <a href="{% url "property:property_list" %}?city=delhi" style="margin-left: 8px;">Delhi</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="footer-links">
                        <h3 class="white">Contact Us</h3>
                        <ul class="mt-20 vfx-footer-list">
                            <li>
                                <div class="vfx-contact-info d-flex  gap-2 align-items-center">
                                    <div class="icon"> <i class="fa fa-map-marker-alt"></i></div>
                                    <div class="text">{{contact_info.address}}</div>
                                </div>
                            </li>
                            <li>
                                <div class="vfx-contact-info d-flex  gap-2 align-items-center">
                                    <div class="icon"><i class="fas fa-envelope"></i></div>
                                    <div class="text"><a href="mailto:{{contact_info.email}}" target="_blank">{{contact_info.email}}</a></div>
                                </div>
                            </li>
                            <li class="">
                                <div class="align-items-center d-flex gap-2 vfx-contact-info">
                                    <div class="icon"><i class="fas fa-phone-alt"></i></div>
                                    <div class="text">{{contact_info.phone}}</div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-copyright pt-2 pb-2">
        <div class="container">
            <div class="copyright-inner d-md-flex align-items-center justify-content-between">
                <div class="copyright-text">
                    <p class="m-0 white">2025 Property. All rights reserved.</p>
                </div>
                <div class="social-links">
                    <ul>
                        {% if site_settings.facebook %}
                            <li><a href="{{site_settings.facebook}}" target="_blank"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
                        {% elif site_settings.twitter %}
                            <li><a href="{{site_settings.twitter}}" target="_blank"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                        {% elif site_settings.instagram %}
                            <li><a href="{{site_settings.instagram}}" target="_blank"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                        {% elif site_settings.linkedin %}
                            <li><a href="{{site_settings.linkedin}}" target="_blank"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
                        {% elif site_settings.pinterest %}
                            <li><a href="{{site_settings.pinterest}}" target="_blank"><i class="fab fa-pinterest" aria-hidden="true"></i></a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

project/templates/customer/partials/header.html
{% load static %}

<header class="main_header_area headerstye-1">
    <div class="header_menu" id="header_menu">
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-flex d-flex align-items-center justify-content-between w-100 pb-3 pt-3">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="{% url "core:home" %}">
                            <img src="{% static "customer/images/24_7_websitelogo.png" %}" alt="image">
                            <img src="{% static "customer/images/24_7_websitelogo.png" %}" alt="image">
                        </a>
                    </div>
                    <div class="navbar-collapse1 d-flex align-items-center" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav" id="responsive-menu">
                            {% url "core:home" as home_url %}
                            {% url "property:property_list" as property_url %}
                            {% url "core:about_us" as about_url %}
                            {% url "core:contact_us" as contact_url %}
                            <li class="dropdown submenu {% if request.path == home_url %}active{% endif %}">
                                <a href="{% url "core:home" %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Home </i></a>
                            </li>
                            <li class="submenu dropdown {% if request.path == property_url %}active{% endif %}">
                                <a href="{% url "property:property_list" %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Listings</a>
                            </li>
                            <li class="{% if request.path == about_url %}active{% endif %}"><a href="{% url "core:about_us" %}">About Us</a></li>
                            <li class="{% if request.path == contact_url %}active{% endif %}"><a href="{% url "core:contact_us" %}">Contact Us</a></li>
                            <li><a href="contact.html" class="d-block d-md-none">Post Property</a></li>
                        </ul>
                    </div>
                    <div class="register-login d-flex align-items-center">
                        {% if not request.user.is_authenticated %}
                            <a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal" class="me-4 white">
                                <i class="fa fa-user"></i>
                                <span class="d-none d-sm-inline-block">&ensp;Login/Register</span>
                            </a>
                        {% else %}
                            <div class="me-2">
                                <a href="{% url "accounts:dashboard" %}" class="cart-icon d-flex align-items-center ms-1"><i class="fa fa-user fs-5 black bg-grey p-2"></i></a>
                            </div>
                        {% endif %}
                        <div class="header_sidemenu me-3">
                            <div class="mhead">
                                <span class="menu-ham">
                                    <a href="#" class="cart-icon d-flex align-items-center ms-1"><i class="fa fa-th-large fs-5 black bg-grey p-2"></i></a>
                                </span>
                            </div>
                        </div>
                        <a href="{% url "property:add_customer_property" %}" class="nir-btn white d-none d-md-block">Post Property<span class="css-1l29bq6">Free</span></a>
                    </div>
                    <div id="slicknav-mobile"></div>
                </div>
            </div>
        </nav>
    </div>
</header>

project/templates/customer/partials/looking_to_buy.html
{% load static %}

<section class="discount-action pt-0 bg-grey">
    <div class="container">
        <div class="call-banner" style="background-image: url({% static "customer/images/looking_to_buy.png" %});">
            <div class="row d-flex align-items-center">
                <div class="col-lg-6 col-md-8 p-0 pt-10">
                    <div class="call-banner-inner bg-theme1 p-5">
                        <div class="trend-content-main">
                            <div class="trend-content p-5">
                                <h5 class="mb-1 white">Wanna to Sell Or Rent??</h5>
                                <h2 class="mb-4"><a class="white">Looking to Buy a New Property or Sell an Existing One?</a></h2>
                                <div class="section-btns d-flex align-items-center">
                                    <a href="{% url "property:add_customer_property" %}" class="nir-btn me-4">Rent Properties <i class="fa fa-arrow-right white pl-1"></i></a>
                                    <a href="{% url "property:property_list" %}" class="nir-btn">Buy Properties <i class="fa fa-arrow-right white pl-1"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-4 p-0"></div>
            </div>
        </div>
        <div class="partner-wrapper bg-white p-4">
            <ul class="attract-slider">
                <li class="px-3"><a href="#"><img src="{% static "customer/images/Ad-Projects/Ad-Projects-2.png" %}" alt=""></a></li>
                <li class="px-3"><a href="#"><img src="{% static "customer/images/Ad-Projects/Ad-Projects-2.png" %}" alt=""></a></li>
                <li class="px-3"><a href="#"><img src="{% static "customer/images/Ad-Projects/Ad-Projects-3.png" %}" alt=""></a></li>
                <li class="px-3"><a href="#"><img src="{% static "customer/images/Ad-Projects/Ad-Projects-4.png" %}" alt=""></a></li>
                <li class="px-3"><a href="#"><img src="{% static "customer/images/Ad-Projects/Ad-Projects-5.png" %}" alt=""></a></li>
                <li class="px-3"><a href="#"><img src="{% static "customer/images/Ad-Projects/Ad-Projects-2.png" %}" alt=""></a></li>
                <li class="px-3"><a href="#"><img src="{% static "customer/images/Ad-Projects/Ad-Projects-3.png" %}" alt=""></a></li>
                <li class="px-3"><a href="#"><img src="{% static "customer/images/Ad-Projects/Ad-Projects-3.png" %}" alt=""></a></li>
            </ul>
        </div>
    </div>
</section>

project/templates/customer/partials/profile-card.html
{% load static %}

{% url "accounts:dashboard" as dashboard_url %}
{% url "accounts:profile" as profile_url %}
{% url "accounts:reviews" as reviews_url %}
{% url "accounts:listing" as listing_url %}
{% url "accounts:history" as history_url %}

<div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
    <div class="dashboard-sidebar">
        <div class="profile-sec">
            <div class="author-news mb-3" style="background-image:url({% static "customer/images/destination/destination16.jpg" %});">
                <div class="author-news-content text-center p-4 py-5">
                    <div class="author-thumb mt-0">
                        {% if request.user.profile %}<img src="{{request.user.profile.url}}" alt="author">{% endif %}
                    </div>
                    <div class="author-content pt-2 p-0">
                        <h3 class="mb-1 white"><a class="white">{{request.user.get_full_name}}</a></h3>
                        {% if request.user.address %}<p class="detail white"><i class="fa fa-map-marker white"></i> {{request.user.address}}</p>{% endif %}
                        {% if request.user.phone %}<p class="detail white"><i class="fa fa-phone white"></i> {{request.user.phone}}</p>{% endif %}
                        <div class="header-social mt-2">
                            <ul>
                                {% if request.user.skype %}<li><a href="{{request.user.skype}}"><i class="fab fa-skype-f"></i></a></li>{% endif %}
                                {% if request.user.facebook %}<li><a href="{{request.user.facebook}}"><i class="fab fa-facebook-f"></i></a></li>{% endif %}
                                {% if request.user.twitter %}<li><a href="{{request.user.twitter}}"><i class="fab fa-twitter-f"></i></a></li>{% endif %}
                                {% if request.user.linkedin %}<li><a href="{{request.user.linkedin}}"><i class="fab fa-linkedin-f"></i></a></li>{% endif %}
                                {% if request.user.instagram %}<li><a href="{{request.user.instagram}}"><i class="fab fa-instagram-f"></i></a></li>{% endif %}
                                {% if request.user.pinterest %}<li><a href="{{request.user.pinterest}}"><i class="fab fa-pinterest-f"></i></a></li>{% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="dot-overlay"></div>
            </div>
        </div>
        <a href="#" class="dashboard-responsive-nav-trigger"><i class="fa fa-reorder"></i> Dashboard Navigation</a>  
        <div class="dashboard-nav">
            <div class="dashboard-nav-inner">
                <ul>
                    <li {% if request.path == dashboard_url %}class="active"{% endif %}><a href="{% url "accounts:dashboard" %}"><i class="fa fa-bars"></i> Dashboard</a></li>
                    <li {% if request.path == profile_url %}class="active"{% endif %}><a href="{% url "accounts:profile" %}"><i class="fa fa-user"></i> Profile</a></li>                     
                    <li {% if request.path == reviews_url %}class="active"{% endif %}><a href="{% url "accounts:reviews" %}"><i class="fa fa-star"></i> Reviews</a></li>
                    <li {% if request.path == listing_url %}class="active"{% endif %}><a href="{% url "accounts:listing" %}"><i class="fa fa-list-alt"></i> Listing</a></li>
                    <li {% if request.path == history_url %}class="active"{% endif %}><a href="{% url "accounts:history" %}"><i class="fa fa-list-ul"></i> Booking History</a></li>
                    <li>
                        <form action="{% url "accounts:logout" %}" method="post" id="logout_form">
                            {% csrf_token %}
                            <a href="javascript:{}" onclick="document.getElementById('logout_form').submit();" id="logout-btn"><i class="fa fa-sign-out-alt"></i> Logout</a>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>